export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_CATEGORY_PRODUCTS: "SET_CATEGORY_PRODUCTS",
  REMOVE_CATEGORY_PRODUCTS: "REMOVE_CATEGORY_PRODUCTS",

  SET_HINT: "SET_HINT",
  UPDATE_HINT: "UPDATE_HINT",
  REMOVE_HINT: "REMOVE_HINT",

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
};
